### ISSUE TITLE
A tiny mistake on example docker-compose file

### ISSUE THREAD

**Issue by x-Felix** [madnuttah/unbound-docker#14]
https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/docker-compose.yaml%20(mcvlan)
Line #72 should be `- <LOCAL_UNBOUND_VOLUME_PATH>/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw`

**Comment by madnuttah** [comment]
Yeah, that is also in the [bridge example](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/docker-compose.yaml%20(bridge)) on line 70. Would you mind creating a pull request for both examples? I'll merge them then.

It should both read 

`- <LOCAL_UNBOUND_VOLUME_PATH>/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw`

Thank you! 💙

**Comment by madnuttah** [comment]
Thank you! Approved and closed.
