### ISSUE TITLE
ZONEMD verification failed: verify DNSKEY RRset with trust anchor failed

### ISSUE THREAD

**Issue by x-Felix** [madnuttah/unbound-docker#19]
Not sure what really happened to my unbound instance after a recreation today. 
Seems like the root.key disappeared and caused SERVFAIL. I download the root.hint and make it work again. And notice a warning message in log. 
```
warning: auth zone .: ZONEMD verification failed: verify DNSKEY RRset with trust anchor failed
info: start of service (unbound 1.17.0). 
```
The auth-zone.conf looks like this. 
`auth-zone:
        name: "."
        primary: 199.9.14.201         # b.root-servers.net
        primary: 192.33.4.12          # c.root-servers.net
        primary: 199.7.91.13          # d.root-servers.net
        primary: 192.5.5.241          # f.root-servers.net
        primary: 192.112.36.4         # g.root-servers.net
        primary: 193.0.14.129         # k.root-servers.net
        primary: 192.0.47.132         # iad.xfr.dns.icann.org
        primary: 192.0.32.132         # lax.xfr.dns.icann.org
        primary: 2001:500:200::b      # b.root-servers.net
        primary: 2001:500:2::c        # c.root-servers.net
        primary: 2001:500:2d::d       # d.root-servers.net
        primary: 2001:500:2f::f       # f.root-servers.net
        primary: 2001:500:12::d0d     # g.root-servers.net
        primary: 2001:7fd::1          # k.root-servers.net
        primary: 2620:0:2830:202::132 # iad.xfr.dns.icann.org
        primary: 2620:0:2d0:202::132  # lax.xfr.dns.icann.org
        #url: "https://www.internic.net/domain/root.zone"
        fallback-enabled: yes
        for-downstream: no
        for-upstream: yes
        zonemd-check: yes
    zonemd-reject-absence: no
        zonefile: "/usr/local/unbound/iana.d/root.zone"`

The security.conf is also exactly as the example.

I notice the root.zone file is also missing under iana.d. I downloaded it manually. But the warning still there. Please help.

**Comment by madnuttah** [comment]
You need to update your root.zone as well, map a docker volume for the iana.d directory and place the file there.

[`iana.org`](https://www.iana.org/domains/root/files)

**Comment by x-Felix** [comment]
Thanks, mapping iana.d solves the issue.

**Comment by madnuttah** [comment]
I will implement an update mechanism for the zone files.

**Comment by madnuttah** [comment]
I'll take a look into that, may it is sufficient having the iana.d mapped but I'll check an update routine as well.

**Comment by madnuttah** [comment]
I've added the mapping to the example docker files
