### ISSUE TITLE
errors in docker-compose.yaml?

### ISSUE THREAD

**Issue by r10513** [madnuttah/unbound-docker#3]
Hi, I am using portainer-ce 2.11.
In order to run the example you made (unbound and pi-hole), I needed to comment all the statement in "volume" section. Otherwise I get several errrors from portainer. With the two sections commented (see below), it works properly.

`#    volumes:` 
`#      - ./pihole/etc/:/etc/:rw`

`#    volumes:`
`#      - ./unbound/:/usr/local/unbound/:rw`
`#      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw`
`#      - ./unbound/log.d/:/usr/local/unbound/log.d/:rw`
`#      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw`

**Comment by madnuttah** [comment]
Hi @r10513. The paths depends on your setup, I modified the example docker-compose.yaml to make it more clear that each value set in angle brackets (<>) have to be edited to suit your environment. Do you need further assistance with the paths?

**Comment by r10513** [comment]
Hi,
Thanks for the quick change. I think it is clearer now.
