### ISSUE TITLE
I need some help with ipv6 setup

### ISSUE THREAD

**Issue by vincentkenny01** [madnuttah/unbound-docker#31]
I have followed your bridge example file and tailored it to my needs but for some reason the DNS queries fail once it is up and running. not sure where I am going wrong but none of the adlist can be updated basically dns fails on pi itself. 

a bit of background, IPv4 setup runs all fine but as my ISP has started IPv6 addresses I thought I would set it all up. In my router, for IPv4 DNS, I have local IP address of Pi and under IPv6 management I have given local link addresses of pi. On pihole admin page, under settings I can see the fd11:aa:1234:1234::505#5335 as default and I can also add this ip 172.20.0.253#5335 manually but it makes no difference. I am not sure where I am going wrong. 

here is my compose file

version: '2'

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    hostname: pi-hole
    
    networks:
      dns-network:
        ipv4_address: 172.20.0.254
        ipv6_address: fd11:aa:1234:1234::506
    dns:
      - 172.20.0.253
      - fd11:aa:1234:1234::505
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:80/tcp"
      - "4443:443/tcp"
    environment:
      ServerIP: 172.20.0.254 
      ServeIP: fd11:aa:1234:1234::506
      WEBPASSWORD: XXXX
      TZ: Europe/London
      PIHOLE_DNS_: 172.20.0.253#5335
      PIHOLE_DNS_: fd11:aa:1234:1234::505#5335
      IPv6: "true"
      
    volumes:
      - '/home/pi/docker/test/etc-pihole/:/etc/pihole/'
      - '/home/pi/docker/test/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
     
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      dns-network:
        ipv4_address: 172.20.0.253
        ipv6_address: fd11:aa:1234:1234::505
    environment: 
      TZ: Europe/London
      ServerIP: 172.20.0.253
      ServerIP: fd11:aa:1234:1234::505
      
    volumes:       
      - /home/pi/docker/test/unbound/unbound.conf:/home/pi/docker/test/unbound/unbound.conf:rw
      - /home/pi/docker/test/unbound/conf.d/:/home/pi/docker/test/unbound/conf.d/:rw
      - /home/pi/docker/test/unbound/log.d/unbound.log:/home/pi/docker/test/unbound/log.d/unbound.log:rw
      - /home/pi/docker/test/unbound/zones.d/:/home/pi/docker/test/unbound/zones.d/:rw
      - /home/pi/docker/test/unbound/iana.d/:/home/pi/docker/test/unbound/iana.d/:rw
      - /home/pi/docker/test/unbound/conf.d/root.hints/:/home/pi/docker/test/unbound/condf.d/root.hints/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
    
networks:
  dns-network:
    enable_ipv6: true #Enable if using IPv6
    driver: bridge

    ipam:
      config:
        - subnet: 172.20.0.0/24     
          gateway: 172.20.0.1  
        - subnet: fd11:aa:1234:1234::/64
          gateway: fd11:aa:1234:1234::11

**Comment by madnuttah** [comment]
Hello and thanks for contacting me!

I don't use IPv6 but I'll try my best to assist you. That's also the reason for taking my examples for IPv6 with a grain of salt. I guess you just left those addresses as they were in my example but you need to adapt these IPv6 addresses to the range your router hands out to your clients using DHCPv6.

The unbound.conf needs to edited to enable IPv6, too. Especially edit the `server:` section the following entries:

`do-ip6: yes`
`access-control: <your IPv6 subnet address> allow`
`interface: ::0@5335`
`private-address: <your IPv6 subnet address> allow`

You might also edit the `local data` and their `ptr` entries as well. Check everything in the conf and run a `unbound-checkconf` to check the config file for errors. 

Also, there's a typo in your Pi-hole compose file. It reads `ServeIP` instead of `ServerIP`.

I hope this helps, don't hesitate to get back to me if you have more questions.

**Comment by madnuttah** [comment]
Another thing, can you ping something in the internet with it's IPv6 address when using your ISP's default DNS servers?

Like `ping -6 unbound.net`?

**Comment by vincentkenny01** [comment]
Hi, thanks for replying. I am completely new to IPv6 so if my questions sounds absurd or out of scope, please let me know but I am trying to start from scratch here. I have read a lot on Docker and IPv6 issues in general (docker supporting IPv4 natively) and unbound in docker not responding on IPv6 but have not came across any working solution. I fully understand that for Pihole to talk to Unbound, it does not need IPv6 or IPv4 and Pihole can manage well with IPv4 only and still provide IPv6 DNS. I am interested and intrigued in making it work in both IPv4 and IPv6 or at least IPv6 only to test it out. 

Under about on my router following is displayed for IPv6.

WAN IP address 2a02:xxxx:x:21f::1599/128
Default gateway	fexx::xx2c:e6ff:fe84:7cda 
DNS server fexx::4ca6:a7a3:d598:950c  <<this is the ip address for pi when i check with ip a at eth0. this was added by me manually under router settings, please see second table below for more.
LAN prefix 2a02:xxxx:xxxx:0000::/64
LAN Link-Local address	fexx::xx21:ecff:fe2c:a275 
WAN Link-Local address	fexx::xx69:1aff:fe12:b600 


Under IPv6 Network management, I have the following options available: (next table below are my current settings)
Internet
Address type : SLAAC, DHCPv6, Manually configure
DNS access: Automatic, Manually configure
Primary DNS server:  <<I can address here in IPv6 format>>
Secondary DNS server: blank 

LAN
Router broadcasting: Automatic, Manually Configure. If I chose manually configure then I get the following option
Prefix: blank <not sure what to add here presuming some sort of fe80..sequence
Prefix length: 64 < changeable 
Preferred lifetime: 3600
Valid lifetime: 7200

DHCP Server: Automatic, Manually configure, Disbaled. If I chose manually configure then I get the following option
Prefix: it has 2001::: address but changeable
Prefix length: 64 < changeable 
Preferred lifetime: 3600
Valid lifetime: 7200
Primary DNS: 2001::: changeable address
Secondary DNS: 2001:::: changeable address

My current configuration for the above is

Internet
Address type : SLAAC
DNS access: Automatic, Manually configure
Primary DNS server:  fexx::4ca6:a7a3:d598:950c
Secondary DNS server: blank 

LAN
Router broadcasting: Automatic
DHCP Server: Automatic


Under pihole settings, DNS I have added Custom IPv6 as ::1#5335

also under etc/docker/daemon.json, I have added the following:

{
  "experimental": true,
  "ip6tables": true
}


If you don't mind helping me with the above setup first so I can then amend the docker-compose.yml file as per your example. I don't know which IPv6 address I should be using and with my limited understanding, the IPv6 address used under docker-compose.yml are created on a separate subnet and not host network which is why I referenced them as per your example.

I think I need a global ipv6 address for the dns to be routable from outside and I don't know if I want to expose this to the world so now I am more confused whether to use local IPv6 address so pihole and unbound talk to each other on IPv6 rather than a fully routable IPv6 DNS open to the world. 

Happy to give more information and make changes as required. 

If you cannot answer/help, no worries as I will carry on experimenting until I get it to work. 

Thanks and Best,

VP

**Comment by madnuttah** [comment]
Sorry for my late reply, it was a quite busy day. **In no way you should expose your local DNS to the internet.** 

Have you considered the changes to the unbound.conf I've suggested in my replies? It's important to set these entries to make at least Unbound able to handle IPv6. 

It might be a good idea to make Pi-hole working first to eliminate another layer of complexity. Use a public DNS as upstream and after you got it working tackle Unbound.

I'd suggest checking if you can ping your router from your computer internally with IPv6. If this works, check if you can ping the Docker host. You can open a shell on the Unbound container using `docker exec -ti unbound sh` please try to `nslookup unbound.net`.

You are of course right, it's a bridge network and not a macvlan so the internal bridge addresses are less important.

Yeah, seems like IPv6 on docker is tricky. Cheers!

**Comment by madnuttah** [comment]
Could you try to add this to the docker daemon.json?

`sudo nano /etc/docker/daemon.json`

```
{
  "ipv6": true, 
  "fixed-cidr-v6": "2001:xxx:x::/64" # Adapt to your IPv6 range here
}
```

and reload docker:

`sudo systemctl reload docker`

**Comment by madnuttah** [comment]
Is there anything I can do? Cheers!

**Comment by vincentkenny01** [comment]
﻿
Hi, sorry just been so busy so haven’t had a chance to look at this. You can close this off as it will take me a little longer to figure out the ipv6 network issue first.  If I get successful, I’ll post my config and steps here. Thanks for your help.


On Aug 21, 2023, at 11:18 AM, ϺΛDИVTTΛH ***@***.***> wrote:

﻿

Is there anything I can do? Cheers!

**Comment by madnuttah** [comment]
Thank you. Sure, feel free to reopen the issue.

Take care!
