### ISSUE TITLE
[Bug] unbound container terminates with "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by madmartin** [madnuttah/unbound-docker#41]
**Describe the bug**
On a Raspberrypi 1B+ (Architecture armv6l) the container immeditately dies after the start with the messages

```
$ docker-compose up
Starting unbound ... done
Attaching to unbound
unbound    | Illegal instruction (core dumped)
unbound exited with code 132
```

**Please complete the following information:**
 - Device: [Raspberry 1 B+]
 - OS: [Debian Bookworm]
 - Architecture: [armv6l]
 - Version [1.19.0-3]

**Additional context**

- I tried the identical docker-compose directory content on an amd64 server - works fine.
- I tried the identical docker-compose directory content on an Raspberry 4 (aarch64)  - works fine.
- I tried older image versions on Raspberry 1B (back to 1.14.0) - all show the same bad behaviour.
- I inspected the image with the command `docker run --rm -it madnuttah/unbound sh` - all usual linux binaries I tried worked well, but all commands in the directory `/usr/local/unbound/unbound.d/sbin` show the same behaviour - terminating with "illegal instruction" message.

So my personal guess is that the unbound binaries are compiled for a different arm variant, not suitable for arm v6l.

**Comment by madnuttah** [comment]
Thank you for reporting this issue and also for contacting me. I'll take a look into this.

**Comment by madmartin** [comment]
Can I find instructions somewhere to self-build the images? Maybe I can find the problem this way?!?

**Comment by madnuttah** [comment]
That would be very helpful indeed since I have no spare Raspberry PI available at the moment and would need to ask you to test the builds or emulate the OS. I guess the main issue is with the OpenSSL build environment where I compile the OpenSSL binaries for the different platforms. So I don't suspect the unbound dockerfile as culprit at the moment but rather [this one](https://github.com/madnuttah/unbound-docker/blob/main/openssl/linux_arm.Dockerfile). 

[OpenSSL build instructions](https://github.com/openssl/openssl/blob/master/INSTALL.md)

[Unbound build instructions](https://unbound.docs.nlnetlabs.nl/en/latest/getting-started/installation.html#building-from-source-compiling)

[More Unbound build instructions](https://github.com/NLnetLabs/unbound/blob/master/doc/README)

Thanks for your thorough bug report, by the way. Good to know that it seems it **never** worked as I've made many changes to the current release. 

Well, bad to know that it seems it never worked. :)

**Comment by madmartin** [comment]
I tried to build the images myself on the Pi with the following commands:

```
#!/bin/bash
#
pushd openssl
docker build -t madnuttah/unbound:openssl-buildenv-3.2.0-2 -f linux_arm.Dockerfile .
popd

pushd libevent/
docker build -t madnuttah/unbound:libevent-buildenv-2.1.12-29 -f Dockerfile .
popd

pushd unbound/
docker build -t madnuttah/unbound:1.19.0-3 -f Dockerfile .
popd
```

The first two build were successful (openssl took many hours...) but the final unbound image failed...
Here are  the last lines of the build process messages:

```
...

 ---> Using cache
 ---> 3dfa2f0a497a
Step 7/20 : RUN set -xe;   apk --update --no-cache add   ca-certificates   gnupg   curl   file   binutils &&   apk --update --no-cache add --virtual .build-deps     build-base     libsodium-dev     linux-headers     nghttp2-dev     expat-dev     protobuf-c-dev     hiredis-dev     apk-tools &&   curl -sSL "$UNBOUND_DOWNLOAD_URL" -o unbound.tar.gz &&   curl -sSL "${UNBOUND_DOWNLOAD_URL}".asc -o unbound.tar.gz.asc &&   echo "${UNBOUND_SHA256} *unbound.tar.gz" | sha256sum -c - &&   GNUPGHOME="$(mktemp -d)" &&   export GNUPGHOME &&   gpg --no-tty --keyserver hkps://keys.openpgp.org --recv-keys "$UNBOUND_PGP" &&   gpg --batch --verify unbound.tar.gz.asc unbound.tar.gz &&   tar -xzf unbound.tar.gz &&   rm unbound.tar.gz &&   cd unbound-${UNBOUND_VERSION} &&   addgroup -S _unbound -g 1000 &&   adduser -S -D -H -h /usr/local/unbound -u 1000 -s /sbin/nologin -G _unbound _unbound &&   ./configure     --prefix=/usr/local/unbound/unbound.d     --with-conf-file=/usr/local/unbound/unbound.conf     --sysconfdir=/usr/local/unbound/unbound.d     --libdir=/usr/local/unbound/unbound.d/lib     --mandir=/usr/share/man     --libexecdir=/usr/local/unbound/unbound.d/lib     --localstatedir=/usr/local/unbound/unbound.d     --with-chroot-dir=/usr/local/unbound     --with-pidfile=/usr/local/unbound/unbound.d/unbound.pid     --with-run-dir=/usr/local/unbound/unbound.d     --with-rootkey-file=/usr/local/unbound/iana.d/root.key     --with-libevent=/usr/local/libevent     --with-ssl=/usr/local/openssl     --with-libnghttp2     --with-libhiredis     --with-username=_unbound     --enable-dnstap     --enable-dnscrypt     --enable-cachedb     --with-pthreads     --without-pythonmodule     --without-pyunbound     --enable-event-api     --enable-tfo-server     --enable-tfo-client     --enable-pie     --enable-relro-now &&   make &&   make install &&   apk del --no-cache .build-deps &&   mkdir -p     "/usr/local/unbound/iana.d/" &&   curl -sSL https://www.internic.net/domain/named.cache -o /usr/local/unbound/iana.d/root.hints &&   curl -sSL https://www.internic.net/domain/named.cache.md5 -o /usr/local/unbound/iana.d/root.hints.md5 &&   curl -sSL https://www.internic.net/domain/named.cache.sig -o /usr/local/unbound/iana.d/root.hints.sig &&   ROOT_HINTS_MD5=`cat /usr/local/unbound/iana.d/root.hints.md5` &&   echo "${ROOT_HINTS_MD5} */usr/local/unbound/iana.d/root.hints" | md5sum -c - &&   curl -sSL https://www.internic.net/domain/root.zone -o /usr/local/unbound/iana.d/root.zone &&   curl -sSL https://www.internic.net/domain/root.zone.md5 -o /usr/local/unbound/iana.d/root.zone.md5 &&   curl -sSL https://www.internic.net/domain/root.zone.sig -o /usr/local/unbound/iana.d/root.zone.sig &&   ROOT_ZONE_MD5=`cat /usr/local/unbound/iana.d/root.zone.md5` &&   echo "${ROOT_ZONE_MD5} */usr/local/unbound/iana.d/root.zone" | md5sum -c - &&   GNUPGHOME="$(mktemp -d)" &&   export GNUPGHOME &&   gpg --no-tty --keyserver hkps://keys.openpgp.org --recv-keys "$INTERNIC_PGP" &&   gpg --verify /usr/local/unbound/iana.d/root.hints.sig /usr/local/unbound/iana.d/root.hints &&   gpg --verify /usr/local/unbound/iana.d/root.zone.sig /usr/local/unbound/iana.d/root.zone &&     /usr/local/unbound/sbin/unbound-anchor -v -a /usr/local/unbound/iana.d/root.key || true &&   pkill -9 gpg-agent &&   pkill -9 dirmngr &&   rm -rf     /usr/share/man     /usr/share/docs     /tmp/*     /var/tmp/*     /var/log/*     /usr/local/libevent/lib/*.la     /usr/local/libevent/bin     /usr/local/libevent/include     /usr/local/libevent/lib/pkgconfig     /usr/local/openssl/misc     /usr/local/openssl/private     /usr/local/openssl/include     /usr/local/openssl/lib/pkgconfig     /usr/local/openssl/lib/*.a     /usr/local/unbound/unbound.d/share     /usr/local/unbound/etc     /usr/local/unbound/unbound.conf     /usr/local/unbound/iana.d/root.hints.*     /usr/local/unbound/iana.d/root.zone.*     /usr/local/unbound/unbound.d/lib/pkgconfig     /usr/local/unbound/unbound.d/include     /usr/local/unbound/unbound.d/lib/*.a     /usr/local/unbound/unbound.d/lib/*.la &&     find /usr/local/libevent/lib/lib* -type f | xargs strip --strip-all &&     find /usr/local/openssl/lib/lib* -type f | xargs strip --strip-all &&     find /usr/local/openssl/lib/engines-3/*.so -type f | xargs strip --strip-all &&     find /usr/local/unbound/unbound.d/lib/lib* -type f | xargs strip --strip-all &&     strip --strip-all /usr/local/unbound/unbound.d/sbin/unbound &&     strip --strip-all /usr/local/unbound/unbound.d/sbin/unbound-anchor &&     strip --strip-all /usr/local/unbound/unbound.d/sbin/unbound-checkconf  &&     strip --strip-all /usr/local/unbound/unbound.d/sbin/unbound-control &&     strip --strip-all /usr/local/unbound/unbound.d/sbin/unbound-host
 ---> Using cache
 ---> 4d866faff124
Step 8/20 : COPY ./unbound/root/usr/local/unbound/   /usr/local/unbound/
COPY failed: file not found in build context or excluded by .dockerignore: stat unbound/root/usr/local/unbound/: file does not exist
```

Any instant idea?

Will continue next days...

**Comment by madnuttah** [comment]
You need to download [this content](https://github.com/madnuttah/unbound-docker/tree/main/unbound/root) and make it available in your build root.

**Comment by madnuttah** [comment]
I've built a dev image for you, @madmartin. Would you test it  [madnuttah/unbound-dev:latest](https://hub.docker.com/r/madnuttah/unbound-dev) if you don't mind please? I've added a new workflow file which should hopefully better support your platform.

**Comment by madmartin** [comment]
Hello @madnuttah - I tried the dev image and its sad to say but the result is the same:

```
$ docker-compose up
Pulling unbound (madnuttah/unbound-dev:latest)...
latest: Pulling from madnuttah/unbound-dev
0803c38384d9: Already exists
8bd2557e7e12: Pull complete
c84268029b7d: Pull complete
8cb8a5b98cd8: Pull complete
Digest: sha256:574fc023a40c7704a5892d10add1fe16575fbf2dfa158a29abf2a7ab613c3343
Status: Downloaded newer image for madnuttah/unbound-dev:latest
Recreating unbound ... done
Attaching to unbound
unbound    | Illegal instruction (core dumped)
unbound exited with code 132
$
```

Meanwhile I adjusted my self-build script (previous fault was to start the final image build from the wrong directory):

```
#!/bin/sh
#
# This script is for those people who want to build the unbound image on their own hardware
# Download a copy of the repository, e.g. with the command
#
#   git clone --depth 1 https://github.com/madnuttah/unbound-docker
#
# and execute this script

OPENSSL_VERSION="3.2.0-2"
LIBEVENT_VERSION="2.1.12-29"
UNBOUND_VERSION="1.19.0-3"


cd $(dirname $0)

docker build -t madnuttah/unbound:openssl-buildenv-$OPENSSL_VERSION -f openssl/linux_arm.Dockerfile .

docker build -t madnuttah/unbound:libevent-buildenv-$LIBEVENT_VERSION -f libevent/Dockerfile .

docker build -t madnuttah/unbound:$UNBOUND_VERSION -t md-madnuttah/unbound:$UNBOUND_VERSION -f unbound/Dockerfile .

```

and the result is a working image.
This script is a quick one, what I dont like very much is the static variable assignment at the beginning, but it works for now.
I would like to see such a script in the repository, so users preferring to have home-made images or use another hardware platform can be made happy.


As a general improvement for your Dockerfiles  I would like to see not to have so many variable assignments with version numbers inside each Dockerfile. I would prefer to have those version numbers at a single place - but at this moment my docker knowledge is not sufficient to judge if this is possible. If you want I can do some research on this. (okay... this discussion is off-topic in this bug report... but I appreciate your comments on that)

**Comment by madnuttah** [comment]
Thanks for your efforts, I like your approach with the script. Would you like to create a PR? Maybe in a subfolder of the root called `scripts`?

**Comment by madmartin** [comment]
Yes I will do.
A second script would be good to create a set of reasonable default configuration files and dirs, and additionally fix permissions.
And an example minimal docker-compose file.
Will file some PRs.

**Comment by madnuttah** [comment]
Thank you!
