### ISSUE TITLE
Could not open xxx: Permission denied" on Synology NAS

### ISSUE THREAD

**Issue by by-carlos** [madnuttah/unbound-docker#42]
I'm trying to run this Unbound container on Synology NAS. Everything looks amazing (is the fastest and easiest one I've tried so far, I'm loving it).

But with this container I'm getting errors accessing the mapped files.

```
[1704707818] unbound[18:0] notice: Start of unbound 1.19.0.
Jan 08 22:56:58 unbound[18:0] error: Could not open logfile /log.d/unbound.log: Permission denied
Jan 08 22:56:58 unbound[18:0] notice: init module 0: validator
Jan 08 22:56:58 unbound[18:0] notice: init module 1: iterator
Jan 08 22:56:58 unbound[18:0] info: start of service (unbound 1.19.0).
Jan 08 22:57:01 unbound[18:0] info: resolving www.com. A IN
Jan 08 22:57:02 unbound[18:0] info: response for www.com. A IN
Jan 08 22:57:02 unbound[18:0] info: reply from (removed)
Jan 08 22:57:02 unbound[18:0] info: query response was ANSWER
Jan 08 22:57:02 unbound[18:0] info: prime trust anchor
Jan 08 22:57:02 unbound[18:0] info: generate keytag query _ta-4f66. NULL IN
Jan 08 22:57:02 unbound[18:0] info: resolving . DNSKEY IN
Jan 08 22:57:02 unbound[18:0] info: resolving _ta-4f66. NULL IN
Jan 08 22:57:02 unbound[18:0] info: response for . DNSKEY IN
Jan 08 22:57:02 unbound[18:0] info: reply from (removed)
Jan 08 22:57:02 unbound[18:0] info: query response was ANSWER
Jan 08 22:57:02 unbound[18:0] fatal error: could not open autotrust file for writing, /iana.d/root.key.18-0-7f1a1630e790: Permission denied
```

I reckon that relates to the user changed, and PUID/PGID are being lost when the user is changed. Only workaround I found was granting RW to Everyone over those files.

How can I map the right user and permissions?

**Comment by madnuttah** [comment]
Hello, many thanks for reaching out and also for your kind words.

The uid/gid 1000 needs write permissions on those folders. It should be sufficient running this recursively on your NAS' unbound root folder: `chown -R 1000:1000 YOURPATHTOUNBOUND`

**Comment by by-carlos** [comment]
Thanks so much. That completely answered my question and took care of the small issue.
