### ISSUE TITLE
New commits but no new release?

### ISSUE THREAD

**Issue by ThaDaVos** [madnuttah/unbound-docker#45]
Sorry for deleting the template, but I thought it was not needed for this as it's really simple - you make new commits but there hasn't been any new Docker hub image release?

**Comment by madnuttah** [comment]
Hi, these commits didn't changed anything related to the image at all, so no new release was published as you can see in the [releases section](https://github.com/madnuttah/unbound-docker/releases). The last release (1.19.0-3) was pushed to Docker hub on 2023-12-08. The only thing updated regarding Unbound were the b-root servers which needs to be updated by each user in their own configs.

**Comment by madnuttah** [comment]
If this didn't answer your question, feel free to reopen.

Thanks.
