### ISSUE TITLE
healthcheck funktioniert nicht mehr

### ISSUE THREAD

**Issue by Radiohofen** [madnuttah/unbound-docker#49]
Hallo,

ich habe gerade Dein neues Image ausgerollt bekommen, In der neuen Version, funktioniert der healthcheck nicht mehr.  Haben sich da Parameter geändert?

So sieht mein docker-compose file aus (siehe Anhang)
![Unbenannt](https://github.com/madnuttah/unbound-docker/assets/160016366/acb49608-05d1-4290-8887-f7479f9f0672)

Mit freundlichen Grüßen
René

**Comment by madnuttah** [comment]
Hallo und danke für deine Anfrage. Ja, der Pfad hat sich geändert und lautet nun: `/usr/local/unbound/sbin/healthcheck.sh`. Ich hab vergessen den Pfad in den [Beispielen](https://github.com/madnuttah/unbound-docker/tree/main/doc/examples) anzupassen. Magst du das eventuell selbst mit einem [PR](https://github.com/madnuttah/unbound-docker/pulls) erledigen? 😉

Ich hoffe ich konnte dein Problem lösen und wünsche dir viel Freude mit dem Image.

Liebe Grüße.

Edit: kompletten Pfad ausgeschrieben

**Comment by Radiohofen** [comment]
Danke Chef hat geholfen! Ich habe die compose files editiert. Ich hoffe, Du kannst die Änderungen so direkt übernehmen?

Falls nicht, sorry bin gerade erst ne Stunde auf Github angemeldet und kenne mich noch nicht aus :-)

Danke für Deine Mühe und Arbeit bei diesem Projekt.

**Comment by madnuttah** [comment]
Danke dir herzlich! Ich mach das dann zu.

Viele Grüße.
