### ISSUE TITLE
The container reports "unhealthy"

### ISSUE THREAD

**Issue by madnuttah** [madnuttah/unbound-docker#53]
The container now reports as unhealty but I am unable to find logs.

_Originally posted by @nick-diama in https://github.com/madnuttah/unbound-docker/issues/50#issuecomment-1945491265_

**Comment by madnuttah** [comment]
I've opened a new issue for you. 

As usual, please post the needed files (config(s), compose and healthcheck file) so I can help you with your problem.

**Comment by nick-diama** [comment]
@madnuttah 
it is solved after I changed in my compose file 
this:
      test: /usr/local/sbin/healthcheck.sh
to this:
      test: /usr/local/unbound/sbin/healthcheck.sh

**Comment by madnuttah** [comment]
Thanks, some paths have changed but they will remain now as they are. I'll close the issue. Feel free to reopen it or to create a new one in case you need further help.

Take care and have fun with the image!
