### ISSUE TITLE
[Bug] healthcheck.sh will check container DNS, not unbound

### ISSUE THREAD

**Issue by kernbug** [madnuttah/unbound-docker#57]
**Describe the bug**
`nslookup internic.net > /dev/null`

**Expected behavior**
`/bin/nslookup -port=5335 -timeout=1 -retry=2 internic.net 127.0.0.1 &> /dev/null`

**Additional context**
Also DNSSEC is not checked with such health check. Maybe worth considering using dig or drill from ldns libs.

**Comment by madnuttah** [comment]
Thanks for checking this so thoroughly, it's **very** appreciated. I'll look into this.

**Comment by madnuttah** [comment]
I think I've got it, will be fixed in the next update. I'll keep this open and inform you then.

Thanks.

**Comment by madnuttah** [comment]
Updated. It'll check for Unbound opened ports. I may look into dig and drill another time.

Thank you.
