### ISSUE TITLE
[Bug] What is the purpose of UNBOUND_UID and UNBOUND_GID, when you do not set anything else other than 1000 (default) in the container ?

### ISSUE THREAD

**Issue by shadarim** [madnuttah/unbound-docker#66]
**Describe the bug**
What is the purpose of UNBOUND_UID and UNBOUND_GID ?
From other containers (e.g. linuxserver/swag), you can specify UID and GID. These are then used by usermod / groupmod at runtime and assigned to the user running in the container. This allows for me to have e.g. UID/GID set to 1104 outside the container and setup folders and files as accessible for this UID/GID combo. Then I pass it to docker in the compose file and no permissions issues. Attempting to do the same does not work for your container. So why specify those as optional at all and list them in your example docker-compose.yml files ? It gives the wrong impression and can lead to difficult to diagnose permissions problems.

Also non-system users start from 1000, so it is common to have already other user at 1000 UID/GID outside docker.

The only other thing I can think of: one can set them if one uses your Dockerfile to build locally...

For reference: [Link](https://github.com/linuxserver/docker-baseimage-alpine/blob/3d21020c647f7a6f12c492e6d640b82c62882c96/root/etc/s6-overlay/s6-rc.d/init-adduser/run#L8)

**To Reproduce**
pass UID/GID other than 1000 (default) in docker-compose.yml --> permissions mayhem --> unbound is not starting

**Expected behavior**
Passing UID/GID other than 1000 (default) in docker-compose.yml will set those UID and GID to the user running in the container

**Please complete the following information:**
 - Device: Rpi 3B
 - OS: Debian Bookworm
 - Architecture: arm64

**Comment by madnuttah** [comment]
Thanks for pointing this out. Yeah, you are absolutely right, I'll make it more clear in the documentation.

**Comment by shadarim** [comment]
May I also suggest, not using the default 1000 when building the container ?
Up to 999 is "reserved" for system accounts, services etc. Maybe use something in the 800s or 900s, so as to not colide with anything outside docker. Then the user can create this UID/GID outside docker and assign the permissions accordingly.

**Comment by madnuttah** [comment]
May I can manage to get the GID/UID stuff running properly for changing the given IDs. I'll take a look in it.

Thank you again for your heads-up!

**Comment by shadarim** [comment]
Maybe you could have a look at the docker` --user` flag - [here](https://docs.docker.com/engine/reference/run/#user).
For now, I personally use the `group_add` directive from docker-compose, to add the _unbound user to a GID, inside the container.

For example:
```
image: madnuttah/unbound:latest
...
group_add:
  - 1234
...
```

I then set permissions to 660/770 for files/folders with UID/GID=1234 outside the container. Seems to work OK.

**Comment by madnuttah** [comment]
Thanks again, it's very appreciated! I'll do some tests.

**Comment by madnuttah** [comment]
Hey @shadarim, I've changed the texts and linked a known issue to your comment as a workaround.

Thank you.

**Comment by madnuttah** [comment]
I've made some progress and it's looking good so far @shadarim.

If there are variables set in the compose file or the command, the _unbound user gets updated and the folder permissions get set for the chosen uid/gid. The changes went into the canary build and the image will be available tonight at about 20:00 UTC.

I'm using an entrypoint script where I user&groupmod as root, set the permissions and then start the unbound process as user `_unbound`.

Would you mind testing it then?

Thank you.

**Comment by madnuttah** [comment]
That commit enables the custom UID/GID feature by passing environment variables to the container besides the possibility to define build args.

**Comment by shadarim** [comment]
Hi, I'm on vacation right now. I'm gonna try to test this next weekend and let you know.

From quick glance at the script.. Not exactly sure what the point of `DISABLE_SET_PERMS` (and the whole if-else for that matter) is? Can you explain?

It creates the possibility to run as root if `user: _unbound` is not set, as you point out in the doc. So is it like a new feature?

**Comment by madnuttah** [comment]
Hey there and thanks for your answer and interest still! 

There will be folder permissions set on container start for the given env vars `UNBOUND_UID` and `UNBOUND_GID` if the env var `DISABLE_SET_PERMS` isn't set or is set to false. For permission actions, root permissions are needed, so the container initializes with `root`, sets permissions and starts Unbound with user `_unbound` then. For users which need a rootless container just like it was before, the env var disables the setting of permissions and starts the whole container including Unbound using the `_unbound` account, it will be UID/GID 1000 for compatibility reasons, though. A drawback or benefit (one can decide) is that if you don't set the user `_unbound` explicitly in your compose or run command, the container is executed completely under root. It's a special use case but this makes the image even more versatile in my opinion. That's the reason I don't mention it in my examples, the majority of users will run the container in the "SET_PERMS" mode.

Sorry for disturbing you on your vacation. I'll keep this open until then.

Hope you like it!

**Comment by shadarim** [comment]
Hi,

sorry for late reply...

The finer nuances of "truely rootless" vs starting as root and dropping privileges are lost on me, I'm afraid. Could you explain how "NOT truely rootless" would lead to greater attack surface here ... I mean we drop back to _unbound user... or am I missing something ?

As I see it `DISABLE_SET_PERMS` could be useful for new setups - e.g. start with root and do not worry about permissions until unbound config is ironed out, then switch to unprivileged UID/GID for "production".

That said, the latest seems to work for my setup now, without adding the `group_add`, which I needed previously.
What I tested:
```
...
environment:
  UNBOUND_UID: 1111
  UNBOUND_GID: 1111
...
```
Container starts and there seem to be no permission problems. Of course unbound files need to be chowned to 1111:1111.

Thanks for looking into it!

**Comment by madnuttah** [comment]
I could imagine use cases where the container should be completely initialized and run rootless, so that's done already too, also the opposite 'rootful' usage. 

Nice that it works for you, I'll close this then. Thank you again.
