### ISSUE TITLE
[Feature Request] add munin for unbound statistic

### ISSUE THREAD

**Issue by mbah-dukun** [madnuttah/unbound-docker#72]
hello, can you add config for add munin?
it can be more info for unbound statistic

**Comment by madnuttah** [comment]
Hello and thanks for your feature request! Supporting a wider variety of monitoring tools would be great but as I'm using Zabbix already, I fear there's just little time to spend on another tool. May you like to chime in and contribute?

I've seen that there's a [plugin available](https://gallery.munin-monitoring.org/plugins/munin-contrib/loggrepx_/) which might achieve similar results by analyzing the statis file created by our healthcheck script?

**Comment by mbah-dukun** [comment]
> Hello and thanks for your feature request! Supporting a wider variety of monitoring tools would be great but as I'm using Zabbix already, I fear there's just little time to spend on another tool. May you like to chime in and contribute?
> 
> I've seen that there's a [plugin available](https://gallery.munin-monitoring.org/plugins/munin-contrib/loggrepx_/) which might achieve similar results by analyzing the statis file created by our healthcheck script?

I've tried creating a dockerfile based on your dockerfile, but failed several times to combine unbound with munin, I took an example of a munin dockerfile from github. apologize in advance as I have no knowledge on this matter. 😓

**Comment by madnuttah** [comment]
Have you seen this?

https://github.com/NLnetLabs/unbound/blob/master/contrib/unbound_munin_

**Comment by madnuttah** [comment]
May [this](https://github.com/NLnetLabs/unbound/blob/master/contrib/unbound_munin_) could do the trick?

**Comment by mbah-dukun** [comment]
im finish to build using grafana & unbound-exporter, thanks for this image ❤

**Comment by madnuttah** [comment]
My pleasure @mbah-dukun!

Would you mind sharing what you did to make it work? We'll all benefit. :)
