### ISSUE TITLE
wrong configuration in latest and canary

### ISSUE THREAD

**Issue by abionescu** [madnuttah/unbound-docker#76]
After upgrade to latest version when I start the container the following error is reported in logs:

UNBOUND_UID: 1000

UNBOUND_GID: 1000

DISABLE_SET_PERMS: false

[1724354003] unbound[7:0] error: cannot parse port number '32768server:'

[1724354003] unbound[7:0] error: Failed to parse the port number

/usr/local/unbound/conf.d/performance.conf:27: error: port number or range ("low-high") expected

read /usr/local/unbound/unbound.conf failed: 1 errors in configuration file

[1724354003] unbound[7:0] fatal error: Could not read config file: /usr/local/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf

**Comment by madnuttah** [comment]
Hi! Please show your configs, yaml and logfiles please. Thank you.

Edit: from which version did you upgrade?

**Comment by abionescu** [comment]
I found it, it was an issue with `performance.conf` for some reason the server part was appended/duplicated after `outgoing-port-permit`
>server:
  num-threads: 4
  num-queries-per-thread: 4096
  cache-max-ttl: 86400
  cache-min-ttl: 300
  edns-buffer-size: 1232
  rrset-roundrobin: yes
  neg-cache-size: 4M
  delay-close: 10000
  rrset-cache-size: 256m
  rrset-cache-slabs: 4
  ratelimit: 1000
  unwanted-reply-threshold: 10000
  infra-cache-slabs: 4
  infra-cache-numhosts: 100000
  msg-cache-size: 256m
  msg-cache-slabs: 4
  key-cache-size: 4m
  key-cache-slabs: 4
  prefetch: yes
  prefetch-key: yes
  serve-expired: yes
  max-udp-size: 4096
  msg-buffer-size: 65552
  stream-wait-size: 4m
  outgoing-range: 32768
  outgoing-port-permit: 32768

Thanks!
For reference the previous version was 1.20.0-5.
